features:
  scaling:
    - s
  normalization_range:
    - 0
    - 1
  node_features:
    - shape
    - vertex
    - facet
    - count
    - min
    - max
    - sum
    - first
    - second  # important feature, only with "first" results are much worse
#    - last # useless feature for object level training, because there are no camera containing tetrahedra
  edge_features:
    - shape
    - vertex
    - facet
    - count
    - min
    - max
    - sum
  node_normalization_feature: null
  edge_normalization_feature: null
graph:
  num_hops: 4 # outer hops (unsupervised) == num_layers
  additional_num_hops: 1 # inner hops (supervised), this is there for having a supervised connected component, if set to 0, only the last layer of num_hops is supervised in the form of unconnected nodes
  clique_sizes: # -1 meaning sample all existing nodes
    - -1
  self_loops: 0
inference:
  dataset: ModelNet10
  shapes_per_conf_per_class: 1
  classes: null
  files: null
#    - monitor_0130
#    - table_0079
#    - chair_0260
#    - monitor_0527
#    - table_0440
#    - chair_0949
  scan_confs:
    - 4
  batch_size: 0   # also for validation
  per_layer: 1    # also for validation
  has_label: 1
  model: 30
  graph_cut: true
  fix_orientation: false
validation:
  dataset: ModelNet10
  shapes_per_conf_per_class: 20
  scan_confs:
    - 4
  batch_size: 0   # also for validation
  per_layer: 1    # also for validation
  val_every: 2
  graph_cut: true
  fix_orientation: true
training:
  dataset: ModelNet10
  classes: null
  data_percentage: 0.9
  shapes_per_conf_per_class: 150
  scan_confs:
    - 4
  files:
    - null
  batch_size: 2048
  epochs: 100
  loss: kl
  learning_rate: 0.005
  adjust_lr_every: 24
  export_every: 5
  load_epoch: 0
retraining:
  load_epoch: 5
  additional_epochs: 4
model:
  type: sage
  encoder: null
  convs: # specify the OUT channels of sage convs
    - 128
    - 256
    - 512
    - 1024
  edge_convs: 1
  decoder: 2
  concatenate: 0 # whether to concatenate (or add) target to source node embedding
  edge_prediction: 0
  normalization: b
time:
  start: ""
  end: ""
paths:
  data: /mnt/raphael/
  out_dir: /mnt/raphael/ModelNet10_out/dgnn/scan4_noreg_gc/
regularization:
  cell_reg_type: vol
  reg_weight: 0.4
  reg_type: null
  reg_epoch: null
  shape_weight_batch_normalization: 1
  inside_outside_weight:
    - 1.0
    - 1.0
