features:
  scaling: s
  normalization_range: [0,1]
  node_features: [shape,vertex,facet,count,min,max,sum,first,second]  # important feature, only with "first" results are much worse
  edge_features: [shape,vertex,facet,count,min,max,sum]
  node_normalization_feature: null
  edge_normalization_feature: null
graph:
  num_hops: 4 # outer hops (unsupervised) == num_layers
  additional_num_hops: 0 # inner hops (supervised), this is there for having a supervised connected component, if set to 0, only the last layer of num_hops is supervised in the form of unconnected nodes
  clique_sizes: [-1] # -1 meaning sample all existing nodes
  self_loops: 0
inference:
  dataset: ShapeNet
  classes: null
  shapes_per_conf_per_class: 10000
  files: null
  scan_confs: [4]
  batch_size: 0
  per_layer: 1
  has_label: 1
  model: best
  graph_cut: 1
  fix_orientation: 1
  export: [ "mesh" ]
  metrics: [ "iou" ]
validation:
  dataset: ShapeNet
  classes: ["04256520","02691156"]
  shapes_per_conf_per_class: 10
  scan_confs: [4]
  batch_size: 0
  per_layer: 1
  graph_cut: true
  fix_orientation: true
  metrics: [ "iou","loss" ]
training:
  dataset: ShapeNet
  classes: ["04256520","02691156","03001627"]
  data_percentage: 0.95
  shapes_per_conf_per_class: 30
  scan_confs: [4]
  files: null
  batch_size: 1024
  epochs: 101
  loss: kl
  learning_rate: 0.005
  adjust_lr_every: 15
  load_epoch: 0
  print_every: 100
  val_every: 1000
  export_every: 50000
model:
  type: sage
  encoder: null
  convs: [128, 256, 512, 1024] # specify the OUT channels of sage convs
  edge_convs: 1
  decoder: 2
  concatenate: 0 # whether to concatenate (or add) target to source node embedding
  edge_prediction: 0
  normalization: b
time:
  start: ""
  end: ""
paths:
  data: /mnt/raphael/
  out: /mnt/raphael/ShapeNet_out/dgnn/scan42/
  train_split: train
  val_split: test
  test_split: test
regularization:
  cell_reg_type: vol
  reg_weight: 0.4
  reg_type: null
  reg_epoch: null
  shape_weight_batch_normalization: 1
  inside_outside_weight: [1.0 1.0]
graph_cut:
  unary_weight: 10
  unary_type: logits
  binary_weight: 10
  binary_type: beta